#!/usr/bin/env bash

#thank goodness for stackoverflow!
#from: stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $DIR

# run api tests
cd api
npm install
npm test

# run app tests
cd ../app
npm install
npm test
